# Generated by Django 5.2.7 on 2025-10-30 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='priority',
            field=models.CharField(choices=[('high', 'high'), ('low', 'low')], default='Low', max_length=30),
            preserve_default=False,
        ),
    ]
