# Generated by Django 5.2.7 on 2025-10-30 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0003_alter_taskmodel_priority_alter_taskmodel_task_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='priority',
            field=models.CharField(choices=[('high', 'High'), ('low', 'Low')], max_length=30),
        ),
    ]
